name: lce-release

on:
  release:
    types: [published]
    tags:
      - v*
  push:
    branches:
      - "releases/nightly"

env:
  IMAGE_NAME: dev

jobs:
  windows-release-wheel:
    name: Build release wheels for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Windows wheels
        run: |
          export PYTHON_BIN_PATH=$(which python)
          export BAZEL_VC="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/"

          python --version
          python -m pip install wheel setuptools numpy six --no-cache-dir

          ./configure.sh

          bazelisk --output_base=cache build :build_pip_pkg --copt=/arch:AVX --enable_runfiles --define=override_eigen_strong_inline=true
          bazel-bin/build_pip_pkg wheelhouse

        shell: bash
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: ${{ runner.os }}-wheels
          path: wheelhouse
